### PR TITLE
Bump to version 0.17.0

### LINKED ISSUE #19: Update recipe to build yapf 0.17.0

### PR DESCRIPTION
**Pull request by TheGhostHuCodes**
Resolves #19

### CODE REVIEW

**Comment by TheGhostHuCodes** [comment]
@vamega,  Huh, looks like my PR build on appvayor failed for:
```
Environment: TARGET_ARCH=x64, CONDA_PY=36, CONDA_INSTALL_LOCN=C:\\Miniconda35-x64
```
because of a timeout while trying to setup the environment. Is there an easy way to get CI to rebuild this PR?

**Comment by vamega** [comment]
I've restarted the appveyor build

**Comment by TheGhostHuCodes** [comment]
@vamega, looks like it went through this time! Anything else I can do to help get this merged in?

**Comment by vamega** [comment]
All merged, thanks for the effort!

**Pull request merged**
