### PR TITLE
Bump version to 0.12.0

### PR DESCRIPTION
**Pull request by vamega**

### CODE REVIEW

**Comment by jakirkham** [comment]
Please [re-render](https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock) the feedstock.

**Comment by jakirkham** [comment]
Please rebase on `master`.

**Comment by vamega** [comment]
Thanks for the help @jakirkham. Expecting it to pass now.

**Comment by jakirkham** [comment]
Of course. If it doesn't, I'd be surprised. So feel free to ping.

**Pull request merged**
